### ISSUE TITLE
fix: please don't use that regex to validate email

### ISSUE THREAD

**Issue by RandalSchwartz** [francescovallone/acanthis#1]
`RegExp(r'^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$')`

No, please don't use this regex to validate email.  It's wrong.  The shortest regex to validate an RFC822 email address is about 2400 characters, and is given in https://www.ex-parrot.com/pdw/Mail-RFC822-Address.html.  Anything shorter is WRONG, unless you're using a grammar, as package:email_validator properly does.  Use that for Dart/Flutter please.

**Comment by francescovallone** [comment]
Thank you for the suggestion and for raising this issue.

I am currently analysing what is the best solution for this problem, as it seems that many people discourage the use of this regex because, as the author stated:

> I do not maintain the underlying regular expression. There may be bugs that have already been fixed in the Perl module. 

And this could lead to bugs that are more difficult to solve, since it would take some time to check the entire expression.

Also, even though I agree with you that the current regex is wrong and should be corrected (thanks again!), I believe that the validation of an email cannot be done just by using a regex, but that additional checks need to be done to certify the validity of an email (for example sending an email to the address you want to validate).

So, as a compromise, I propose using this regex which should give a good degree of validity while remaining fairly simple and straightforward:
```regex
[a-z0-9! #$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?
```

**Comment by francescovallone** [comment]
Ultimately, I opted to use the email_validator package to validate emails as you suggested in the issue.

This change will be available in the next version of the package 😃.
